import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import {validateUslugiLead,createUslugiLeadHandler,readUslugiLeads,isUslugiHost} from '../uslugi-leads.mjs';
const input={name:'Тест',phone:'+79990000000',clientType:'Частный дом',consent:true,service:'Промывка',message:'Тест без внешней отправки'};
test('host isolation and server validation',()=>{assert.equal(isUslugiHost({hostname:'electro.seti96.ru'}),false);assert.equal(isUslugiHost({hostname:'uslugi.seti96.ru'}),true);for(const patch of [{consent:false},{phone:'123'},{website:'bot'},{clientType:'other'}])assert.equal(validateUslugiLead({...input,...patch}).status,400);assert.equal(validateUslugiLead(input).lead.phone,input.phone)});
function response(){return{code:200,data:null,status(code){this.code=code;return this},json(data){this.data=data;return this}}}
test('only confirmed delivery succeeds; client relay flag cannot spoof success',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'seti96-lead-test-'));try{const handler=createUslugiLeadHandler({dataDir:dir,publicRelayUrl:'',deliverDirect:async()=>({ok:false}),env:{}});const res=response();await handler({hostname:'uslugi.seti96.ru',body:{...input,clientRelayDelivered:true}},res,()=>{});assert.equal(res.code,502);assert.equal(res.data.saved,true);const rows=await readUslugiLeads(dir);assert.equal(rows.length,1);assert.equal(rows[0].telegram_status,'доставка не настроена')}finally{await cleanup(dir)}});
test('parallel requests preserve all records and delivery status',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'seti96-lead-test-'));try{let delivered=0;const handler=createUslugiLeadHandler({dataDir:dir,publicRelayUrl:'',deliverDirect:async()=>{delivered++;return{ok:true}},env:{TELEGRAM_BOT_TOKEN:'test-only',TELEGRAM_CHAT_ID:'test-only'}});const responses=await Promise.all(Array.from({length:12},async(_,i)=>{const res=response();await handler({hostname:'uslugi.seti96.ru',body:{...input,phone:'+7999000'+String(i).padStart(4,'0')}},res,()=>{});return res}));assert.ok(responses.every(x=>x.code===200&&x.data.ok));const rows=await readUslugiLeads(dir);assert.equal(rows.length,12);assert.equal(new Set(rows.map(x=>x.id)).size,12);assert.equal(delivered,12);assert.ok(rows.every(x=>x.telegram_status==='доставлено (напрямую)'))}finally{await cleanup(dir)}});
test('calculator applies service minimum, zone minimum and heavy transport',async()=>{const source=await readFile(new URL('../uslugi-static/app.js',import.meta.url),'utf8');const context=vm.createContext({document:{querySelector:()=>null,querySelectorAll:()=>[],addEventListener:()=>{}},location:{search:''},URLSearchParams,Intl,localStorage:{getItem:()=>null},window:{}});vm.runInContext(source,context);const compute=(s,q,z,h=false)=>context.estimate(s,q,z,h);const s={low:30000,high:35000,minimum:30000,heavy:true};assert.equal(compute(s,1,0).low,30000);assert.equal(compute(s,1,1).low,34500);assert.equal(compute(s,1,2).high,42500);assert.equal(compute({low:900,high:1800,minimum:5000},1,0).low,5000);assert.equal(compute({low:900,high:1800,minimum:5000},1,1).low,11000);assert.equal(compute(s,1,4).custom,true);assert.equal(compute({...s,monthly:true},1,0).custom,true)});

async function cleanup(dir){const resolved=path.resolve(dir);assert.equal(path.dirname(resolved),path.resolve(tmpdir()));assert.ok(path.basename(resolved).startsWith('seti96-lead-test-'));await rm(resolved,{recursive:true,force:true})}

test('browser relay accepts only the uslugi parent and confirmed gateway success',async()=>{
 const html=await readFile(new URL('../prochistka-static/uslugi-relay.html',import.meta.url),'utf8');
 const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];let listener,calls=0,ok=true;const messages=[];
 const parent={postMessage:(message,origin)=>messages.push({message,origin})};
 vm.runInNewContext(script,{window:{addEventListener:(_,fn)=>listener=fn},parent,AbortSignal,fetch:async()=>{calls++;return{ok:true,json:async()=>({ok})}}});
 const event={origin:'https://uslugi.seti96.ru',source:parent,data:{type:'uslugi-lead',id:'test',payload:input}};
 await listener({...event,origin:'https://untrusted.invalid'});await listener({...event,source:{}});assert.equal(calls,0);
 await listener(event);assert.equal(calls,1);assert.equal(messages.at(-1).message.ok,true);assert.equal(messages.at(-1).origin,event.origin);
 ok=false;await listener(event);assert.equal(messages.at(-1).message.ok,false);
});
test('local browser receipt cannot become server-confirmed delivery or resend a lead',async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'seti96-lead-test-'));
 try{const handler=createUslugiLeadHandler({dataDir:dir,env:{},deliverDirect:async()=>{throw Error('duplicate')},fetchImpl:async()=>{throw Error('duplicate')}});const res=response();await handler({hostname:'uslugi.seti96.ru',body:{...input,browserRelayReceipt:true}},res,()=>{});assert.equal(res.code,202);assert.equal(res.data.saved,true);assert.equal(res.data.ok,undefined);assert.match((await readUslugiLeads(dir))[0].telegram_status,/сервером не проверено/)}finally{await cleanup(dir)}
});

test('existing company relay works when Timeweb has no Telegram secrets',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'seti96-lead-test-'));try{let request;const handler=createUslugiLeadHandler({dataDir:dir,env:{LEAD_RELAY_URL:'https://old-relay.invalid',LEAD_RELAY_SECRET:'test-only'},deliverDirect:async()=>{throw Error('must not call direct')},fetchImpl:async(url,options)=>{request={url,body:JSON.parse(options.body)};assert.equal(options.headers['user-agent'],'SETI96/1.0 (+https://uslugi.seti96.ru)');return{ok:true,json:async()=>({ok:true,delivery:'доставлено'})}}});const res=response();await handler({hostname:'uslugi.seti96.ru',body:{...input,address:'Тестовый район'}},res,()=>{});assert.equal(res.data.ok,true);assert.equal(request.url,'https://seti96-engineering.german123312.chatgpt.site/api/leads');assert.equal(request.body.service,input.service);assert.equal(request.body.message,input.message);assert.equal(request.body.address,'Тестовый район');assert.equal(request.body.consent,true);assert.equal(request.body.secret,undefined);assert.equal((await readUslugiLeads(dir))[0].telegram_status,'доставлено (шлюз)')}finally{await cleanup(dir)}});
test('relay rejection does not turn into a successful request',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'seti96-lead-test-'));try{const handler=createUslugiLeadHandler({dataDir:dir,env:{},deliverDirect:async()=>({ok:false}),fetchImpl:async()=>({ok:true,json:async()=>({ok:false})})});const res=response();await handler({hostname:'uslugi.seti96.ru',body:input},res,()=>{});assert.equal(res.code,502);assert.equal(res.data.saved,true)}finally{await cleanup(dir)}});
