"use client";
import {useEffect,useState} from "react";
const phone="+7 993 106-04-23",tel="tel:+79931060423";
const email="seti-96@yandex.ru";
const articles=[["Когда требуется промывка системы отопления частного дома","Частный дом"],["Почему газовый котёл стал хуже греть","Котлы и бойлеры"],["Как проходит химическая промывка теплообменника","Теплообменники"],["Почему батареи нагреваются неравномерно","Частный дом"],["Когда требуется промывка контуров тёплого пола","Частный дом"],["Химическая и гидропневматическая промывка: в чём разница","Теплообменники"],["Как проводится промывка ИТП и теплового пункта","Управляющим компаниям"],["Подготовка многоквартирного дома к отопительному сезону","Подготовка к сезону"],["Зачем нужна опрессовка системы отопления","Подготовка к сезону"],["Может ли система потечь после промывки","Теплообменники"],["От чего зависит стоимость промывки отопления","Частный дом"],["Как накипь влияет на работу котла и теплообменника","Котлы и бойлеры"]];
const faqs=[["Когда системе требуется промывка?","Если оборудование дольше нагревается, шумит, перегревается, а радиаторы или контуры работают неравномерно. Такие признаки имеют разные причины, поэтому сначала нужен осмотр."],["Можно ли выполнить промывку без демонтажа?","Да, когда конструкция и состояние оборудования позволяют подключить промывочную установку к закрытому контуру."],["Сколько времени занимает работа?","Зависит от объёма системы, характера отложений и доступа к точкам подключения. Срок специалист определит после осмотра."],["Подходит ли один реагент для любого оборудования?","Нет. Концентрация, температура и продолжительность обработки подбираются с учётом материала и состояния оборудования."],["Может ли после удаления отложений обнаружиться течь?","Плотные отложения иногда скрывают уже существующую коррозию. После их удаления может обнаружиться негерметичность, существовавшая до промывки."],["Можно ли гарантировать снижение расхода газа?","Если снижение эффективности связано с отложениями, очистка может восстановить теплоотдачу. Фактический результат зависит от состояния оборудования и причины неисправности."]];
export default function SiteShell({page="home"}:{page?:string}){
 const [modal,setModal]=useState(false),[sent,setSent]=useState(false),[cookie,setCookie]=useState(true),[phoneInput,setPhoneInput]=useState("+7");
 useEffect(()=>setCookie(localStorage.getItem("cookie-ok")!=="1"),[]);
 const metricGoal=(goal:string)=>{const w=window as Window&{ym?:(id:number,action:string,goal:string)=>void};w.ym?.(111900032,"reachGoal",goal)};
 const openModal=()=>{metricGoal("callback_open");setSent(false);setPhoneInput("+7");setModal(true)};
 const lead=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const phoneField=e.currentTarget.elements.namedItem("phone") as HTMLInputElement,digits=phoneInput.replace(/\D/g,"");if(digits.length!==11||digits[0]!=="7"){phoneField.setCustomValidity("Введите 10 цифр номера после +7");phoneField.reportValidity();return}phoneField.setCustomValidity("");const f=new FormData(e.currentTarget);f.set("phone","+7"+digits.slice(1));const clientType=String(f.get("clientType")||"");const q=new URLSearchParams(location.search),data={...Object.fromEntries(f),source:document.referrer||"Прямой переход",utm_campaign:q.get("utm_campaign")||"",utm_content:q.get("utm_content")||"",utm_term:q.get("utm_term")||""};const res=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});if(res.ok){metricGoal("lead_success");metricGoal(clientType==="Частный дом"?"private_lead":"organization_lead");setSent(true)}};
 const cta=<><button className="btn primary" onClick={openModal}>Заказать звонок</button><a className="btn ghost" href={tel} onClick={()=>metricGoal("phone_click")}>Позвонить</a></>;
 return <div className="site"><header><a href="/" className="logo" aria-label="Сети96 — главная"><img src="/media/seti96-logo.png" alt="Сети96"/></a><nav><a href="/">Главная</a><a href="/dom">Частный дом</a><a href="/organizaciyam">Организациям</a><a href="/materialy">Материалы</a><a href="/kontakty">Контакты</a></nav><a className="headphone" href={tel} onClick={()=>metricGoal("phone_click")}>{phone}</a><button className="mini" onClick={openModal}>Заказать звонок</button></header>
 {page==="home"&&<><section className="hero dark"><div className="hero-copy"><p className="eyebrow">Екатеринбург · Свердловская область</p><h1>Химическая промывка <em>котлов, теплообменников</em> и систем отопления</h1><p className="lead">Удаляем накипь, ржавчину и минеральные отложения профессиональным составом на основе органических кислот. Работаем с объектами от бытового бойлера до многоквартирного дома.</p><div className="free"><span>01</span><b>Бесплатный выезд специалиста</b><small>для осмотра объекта и расчёта стоимости</small></div><div className="actions">{cta}</div></div><div className="homeHeroMedia"><figure><img src="/media/heat-exchangers-before-after.png" alt="Пластинчатый теплообменник до и после очистки"/></figure><div className="machine"><div className="dial">96</div><div className="pipe p1"/><div className="pipe p2"/><div className="caption">ЦИРКУЛЯЦИОННАЯ<br/>ПРОМЫВКА</div></div></div></section><div className="audience"><a className="active" href="/dom">Для частного дома</a><a href="/organizaciyam">Для организаций и УК</a><p>Выберите подходящий раздел, чтобы посмотреть перечень работ и условия. <a href="/dom">Частный дом →</a> <a href="/organizaciyam">Организациям →</a></p></div><section className="light problems"><div><p className="eyebrow ink">Диагностика</p><h2>Когда системе может потребоваться промывка</h2><p>Признаки не всегда означают загрязнение. Перед работами инженер оценит систему и определит, даст ли промывка необходимый результат.</p></div><ul>{["Медленный нагрев воды","Неравномерно греются батареи","Тёплый пол потерял эффективность","Шум при нагреве","Долгий выход на температуру","Перегрев теплообменника","Перепады температуры","Ржавчина в теплоносителе"].map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</li>)}</ul></section><section className="split dark"><a href="/dom"><small>ЧАСТНЫМ КЛИЕНТАМ</small><h2>Для дома</h2><p>Котлы, бойлеры, теплообменники, радиаторы, трубы и тёплый пол.</p><b>Перейти →</b></a><a href="/organizaciyam"><small>B2B / ЖКХ</small><h2>Для организаций</h2><p>ИТП, тепловые пункты, МКД, коммерческие и производственные объекты.</p><b>Перейти →</b></a></section><Process/><Reagent/><Faq/></>}
 {page==="dom"&&<Inner heroImage="/media/radiator-thermal-before-after.png" heroAlt="Термограмма радиатора до и после промывки" title="Промывка отопления, котлов и теплообменников в частном доме" eyebrow="Частным владельцам" intro="Поможем восстановить нормальную циркуляцию и теплоотдачу без дорогостоящей замены исправного оборудования, если причиной проблемы являются внутренние отложения." items={["Газовые и электрические котлы","Твердотопливные котлы","Теплообменники и бойлеры","Радиаторы и трубы","Контуры тёплого пола","Вся система отопления дома"]} cta={cta}/>} 
 {page==="org"&&<Inner heroImage="/media/plate-heat-exchanger-before-after.png" heroAlt="Пластинчатый теплообменник до и после очистки" title="Промывка ИТП, теплообменников и систем отопления для организаций" eyebrow="УК · ТСЖ · предприятия" intro="Бесплатно обследуем объект, подберём технологию и подготовим расчёт стоимости. Работаем по договору и согласованному регламенту." items={["ИТП и тепловые пункты","Пластинчатые теплообменники","Кожухотрубные теплообменники","Котельное оборудование","Системы отопления зданий","Промывка и опрессовка","Подготовка к отопительному сезону","Акты и фотофиксация"]} cta={cta}/>} 
 {page==="blog"&&<section className="page light"><p className="eyebrow ink">Инженерная база знаний</p><h1>Полезные материалы</h1><p className="intro">Понятно о промывке, обслуживании и ограничениях технологии.</p><div className="articles">{articles.map(([t,c],i)=><article key={t}><small>{c}</small><h3>{t}</h3><p>Разбираем признаки, возможные причины и порядок действий без лишних обещаний.</p><a href={`/materialy/statya-${i+1}`}>Читать →</a></article>)}</div></section>}
 {page==="contacts"&&<section className="page dark contact"><p className="eyebrow">Связаться</p><h1>Контакты «Сети 96»</h1><p className="contactIntro">Работаем в Екатеринбурге и Свердловской области. Бесплатно выезжаем на объект для осмотра и расчёта стоимости.</p><div className="contactList"><div><small>Телефон</small><a href={tel} onClick={()=>metricGoal("phone_click")}>{phone}</a></div><div><small>Адрес</small><a href="https://yandex.ru/maps/?text=Екатеринбург%2C%20ул.%20Хасановская%2C%2068" target="_blank" rel="noreferrer">Екатеринбург, ул. Хасановская, 68</a></div><div><small>Электронная почта</small><a href={`mailto:${email}`} onClick={()=>metricGoal("email_click")}>{email}</a></div></div><div className="region"><span>66</span><div><b>Свердловская область</b><small>Частные дома, УК, ТСЖ и организации</small></div></div><div className="actions">{cta}</div></section>}
 <section className="final"><p className="eyebrow ink">Первый шаг</p><h2>Бесплатно выедем на объект<br/>и рассчитаем стоимость</h2><p>Осмотрим систему, уточним объём и сложность работ, подберём способ промывки.</p><div className="actions">{cta}</div></section><footer><a href="/" className="logo" aria-label="Сети96 — главная"><img src="/media/seti96-logo.png" alt="Сети96"/></a><p>ООО «Танзанит»<br/>ИНН 6670234728 · ОГРН 1086670038509<br/>Юр. адрес: г. Екатеринбург, ул. Вишнёвая, д. 69Б, офис 9</p><a href="/politika">Политика обработки персональных данных</a><a href="/admin">Администратору</a><small>© 2026 Сети96</small></footer><div className="mobilebar">{cta}</div>
 {cookie&&<div className="cookie">Используем cookie для работы сайта и аналитики. <button onClick={()=>{localStorage.setItem("cookie-ok","1");setCookie(false)}}>Понятно</button></div>}
 {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><div className="modal"><button className="close" onClick={()=>setModal(false)}>×</button>{sent?<div className="success"><b>Заявка принята</b><p>Специалист «Сети96» скоро свяжется с вами.</p></div>:<><p className="eyebrow ink">Обратный звонок</p><h2>Заказать звонок</h2><form onSubmit={lead}><label>Ваше имя<input name="name" required autoComplete="name"/></label><label>Телефон<input name="phone" required inputMode="tel" placeholder="+7 (999) 000-00-00" autoComplete="tel" value={phoneInput} onChange={e=>{setPhoneInput(e.target.value);e.target.setCustomValidity("")}}/></label><fieldset><legend>Тип клиента</legend><label><input type="radio" name="clientType" value="Частный дом" defaultChecked/> Частный дом</label><label><input type="radio" name="clientType" value="УК / организация"/> УК / организация</label></fieldset><input type="hidden" name="page" value={page}/><label className="agree"><input type="checkbox" required/> Согласен на <a href="/politika" target="_blank" rel="noreferrer">обработку персональных данных</a></label><button className="btn primary" type="submit">Заказать звонок</button></form></>}</div></div>}
 </div>}
function Process(){return <section className="process dark"><p className="eyebrow">Технология</p><h2>Как проходит промывка</h2><div className="steps">{["Звонок и уточнение задачи","Бесплатный выезд","Осмотр и расчёт","Согласование технологии","Подключение установки","Циркуляция раствора","Контроль очистки","Промывка водой","Проверка результата"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></div>)}</div><div className="scheme"><b>ПРОМЫВОЧНАЯ УСТАНОВКА</b><i>→</i><span>Подающий шланг</span><i>→</i><b>ОЧИЩАЕМЫЙ КОНТУР</b><i>→</i><span>Обратный шланг</span><i>↩</i></div></section>}
function Reagent(){return <section className="reagent light"><div><p className="eyebrow ink">Собственная разработка</p><h2>Состав на основе органических кислот</h2><p>Концентрация и продолжительность обработки подбираются с учётом материала оборудования, объёма системы и характера загрязнений.</p><ul><li>Растворяет накипь и минеральные отложения</li><li>Работает внутри закрытого контура</li><li>Процесс контролирует специалист</li><li>После обработки система промывается водой</li></ul></div><figure className="reagentMedia"><img src="/media/pipes-before-after.png" alt="Труба до и после химической очистки"/></figure></section>}
function Faq(){return <section className="faq light"><p className="eyebrow ink">Вопросы и ответы</p><h2>Без скрытых условий</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>}
function Inner({title,eyebrow,intro,items,cta,heroImage,heroAlt,secondaryHeroImage,secondaryHeroAlt}:{title:string;eyebrow:string;intro:string;items:string[];cta:React.ReactNode;heroImage:string;heroAlt:string;secondaryHeroImage?:string;secondaryHeroAlt?:string}){return <><section className={`innerHero dark${secondaryHeroImage?" innerHeroWithStack":""}`}><div className="innerCopy"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p><div className="actions">{cta}</div></div><div className="innerHeroMediaStack">{secondaryHeroImage&&<figure className="innerHeroMedia"><img src={secondaryHeroImage} alt={secondaryHeroAlt}/></figure>}<figure className="innerHeroMedia"><img src={heroImage} alt={heroAlt}/><figcaption>Техническая иллюстрация</figcaption></figure></div></section><section className="serviceList light"><h2>Что промываем</h2><div>{items.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3></article>)}</div><p className="notice">Стоимость зависит от типа оборудования, объёма системы, материала, степени загрязнения и сложности подключения. Специалист бесплатно выедет на объект и рассчитает стоимость до начала работ.</p></section><Process/><Faq/></>}
